import type {
  DoctrineAction,
  DoctrineAuthoringRelease,
  DoctrineContradiction,
  DoctrineRule,
} from "./schemas";

const ROOT_FIXTURES = [
  {
    action: "reflect.lead-listen",
    constructive: ["direction", "independence", "initiative"],
    prompt: "Where can you lead while still listening?",
    root: 1,
    tensions: ["domination", "impatience", "isolation"],
  },
  {
    action: "reflect.boundary",
    constructive: ["cooperation", "diplomacy", "sensitivity"],
    prompt: "What boundary would make cooperation more honest?",
    root: 2,
    tensions: ["conflict_avoidance", "indecision", "over-accommodation"],
  },
  {
    action: "reflect.finish-idea",
    constructive: ["creativity", "expression", "sociability"],
    prompt: "What idea deserves a finished form?",
    root: 3,
    tensions: ["performance", "scattering", "unfinished_work"],
  },
  {
    action: "reflect.review-routine",
    constructive: ["craft", "reliability", "structure"],
    prompt: "Which routine serves you, and which has become a cage?",
    root: 4,
    tensions: ["fear_of_change", "overwork", "rigidity"],
  },
  {
    action: "reflect.reversible-experiment",
    constructive: ["adaptability", "freedom", "movement"],
    prompt: "What reversible experiment could channel the need for change?",
    root: 5,
    tensions: ["excess", "impulsivity", "restlessness"],
  },
  {
    action: "reflect.care-boundary",
    constructive: ["beauty", "care", "responsibility"],
    prompt: "What care can be offered without taking over?",
    root: 6,
    tensions: ["control_through_helping", "guilt", "perfectionism"],
  },
  {
    action: "reflect.evidence-question",
    constructive: ["analysis", "inquiry", "privacy"],
    prompt: "What question benefits from evidence and what needs lived experience?",
    root: 7,
    tensions: ["detachment", "isolation", "suspicion"],
  },
  {
    action: "reflect.responsible-power",
    constructive: ["authority", "organization", "stewardship"],
    prompt: "What would responsible power look like here?",
    root: 8,
    tensions: ["harshness", "overcontrol", "status_fixation"],
  },
  {
    action: "reflect.complete-release",
    constructive: ["compassion", "completion", "service"],
    prompt: "What can be completed or released without self-erasure?",
    root: 9,
    tensions: ["difficulty_releasing", "diffuse_boundaries", "saviorism"],
  },
] as const;

function rootRule(fixture: (typeof ROOT_FIXTURES)[number]): DoctrineRule {
  return {
    actionKeys: [fixture.action],
    claims: {
      en: [
        `Within this modern Western Life Path profile, root ${fixture.root} is associated with ${fixture.constructive.join(
          ", ",
        )}; its balancing prompts include ${fixture.tensions.join(", ")}.`,
      ],
      hi: [],
      or: [],
    },
    conditions: [{ op: "eq", path: "fact.root", value: fixture.root }],
    confidence: "medium",
    exclusions: [],
    metricId: "life_path",
    profileId: "western_decoz_v1",
    ruleId: `western.life-path.${fixture.root}.v1`,
    safetyTags: ["agency", "attributed", "reflective"],
    sourceRefs: [
      {
        evidenceClass: "derived_product_policy",
        locator: `Document 4 root-number theme ontology, root ${fixture.root}`,
        sourceId: "SRC-POLICY-ROOT-ONTOLOGY",
      },
    ],
    status: "active",
    themes: [...fixture.constructive, ...fixture.tensions],
    valence: "contextual",
    version: "1.0.0",
  };
}

function action(fixture: (typeof ROOT_FIXTURES)[number]): DoctrineAction {
  return {
    actionKey: fixture.action,
    instructions: { en: [fixture.prompt] },
    safetyTags: ["agency", "low_cost", "reflective", "reversible"],
    status: "active",
    version: "1.0.0",
  };
}

const CONTRADICTIONS: readonly DoctrineContradiction[] = [
  {
    contradictionId: "CONTRA-HIST-001",
    dimension: "historical_origin",
    positionA: "direct_ancient_pythagorean_lineage",
    positionB: "number_philosophy_without_modern_formulas",
    profileA: "modern_western",
    profileB: "historical_evidence",
    resolution: "separate_precursor_from_formula_origin",
  },
  {
    contradictionId: "CONTRA-LP-001",
    dimension: "life_path_reduction",
    positionA: "component_reduction",
    positionB: "continuous_digit_sum",
    profileA: "western_decoz_v1",
    profileB: "western_digit_sum_v1",
    resolution: "compare_profiles",
  },
  {
    contradictionId: "CONTRA-CHEIRO-DOB-001",
    dimension: "full_date",
    positionA: "combine_components",
    positionB: "keep_day_month_year_distinct",
    profileA: "western_decoz_v1",
    profileB: "cheiro_1926_v1",
    resolution: "profile_boundary",
  },
  {
    contradictionId: "CONTRA-MASTER-001",
    dimension: "masters",
    positionA: "retain_11_22_33_selected_metrics",
    positionB: "no_master_nonreduction",
    profileA: "western_decoz_v1",
    profileB: "cheiro_1926_v1",
    resolution: "profile_boundary",
  },
  {
    contradictionId: "CONTRA-COMP-001",
    dimension: "compound",
    positionA: "karmic_debts_13_14_16_19",
    positionB: "individual_compounds_10_plus",
    profileA: "modern_western",
    profileB: "cheiro_1926_v1",
    resolution: "never_translate",
  },
  {
    contradictionId: "CONTRA-NAME-001",
    dimension: "name_scope",
    positionA: "full_birth_name",
    positionB: "socially_dominant_name",
    profileA: "western_decoz_v1",
    profileB: "cheiro_1926_v1",
    resolution: "separate_name_use",
  },
  {
    contradictionId: "CONTRA-MAP-001",
    dimension: "letter_mapping",
    positionA: "C3_H5_X5",
    positionB: "C2_H8_X6",
    profileA: "cheiro_1926_v1",
    profileB: "indian_johari_1990_v1",
    resolution: "immutable_table_id",
  },
  {
    contradictionId: "CONTRA-Y-001",
    dimension: "y_classification",
    positionA: "pronunciation_context",
    positionB: "fixed_category",
    profileA: "western_contextual_v1",
    profileB: "western_fixed_y_v1",
    resolution: "occurrence_level_policy",
  },
  {
    contradictionId: "CONTRA-DATE-001",
    dimension: "date_boundary",
    positionA: "midnight",
    positionB: "pre_dawn_previous_day",
    profileA: "civil_default",
    profileB: "johari_predawn_v1",
    resolution: "explicit_place_time_policy",
  },
  {
    contradictionId: "CONTRA-PY-001",
    dimension: "personal_year_boundary",
    positionA: "calendar_year",
    positionB: "birthday_to_birthday",
    profileA: "western_decoz_v1",
    profileB: "western_birthday_v1",
    resolution: "separate_intervals",
  },
  {
    contradictionId: "CONTRA-CHALLENGE-001",
    dimension: "challenge_timing",
    positionA: "fluid_and_third_lifelong",
    positionB: "pinnacle_aligned",
    profileA: "decoz_interpretation",
    profileB: "common_app_profile",
    resolution: "separate_timing_profile",
  },
  {
    contradictionId: "CONTRA-JYEAR-001",
    dimension: "year_formula",
    positionA: "full_calendar_year_digits",
    positionB: "last_two_digits_plus_weekday",
    profileA: "western_decoz_v1",
    profileB: "indian_johari_1990_v1",
    resolution: "distinct_metric",
  },
  {
    contradictionId: "CONTRA-LOSHU-001",
    dimension: "grid_population",
    positionA: "raw_nonzero_digits",
    positionB: "add_psychic_and_destiny",
    profileA: "loshu_raw_dob_v1",
    profileB: "loshu_indian_augmented_v1",
    resolution: "compare_profiles",
  },
  {
    contradictionId: "CONTRA-GRID-001",
    dimension: "coordinates",
    positionA: "4_9_2_grid",
    positionB: "3_6_9_grid",
    profileA: "loshu_raw_dob_v1",
    profileB: "phillips_templeton_birth_chart_v1",
    resolution: "separate_systems",
  },
  {
    contradictionId: "CONTRA-ARROW-001",
    dimension: "arrow_labels",
    positionA: "conflicting_names",
    positionB: "stable_triples",
    profileA: "loshu_sources",
    profileB: "neutral_geometry",
    resolution: "use_alias_dictionary",
  },
  {
    contradictionId: "CONTRA-PHONE-001",
    dimension: "phone_scope",
    positionA: "line_or_last_digits",
    positionB: "ten_digit_subscriber",
    profileA: "world_numerology",
    profileB: "indian_phone_profiles",
    resolution: "explicit_view_policy",
  },
  {
    contradictionId: "CONTRA-HOUSE-001",
    dimension: "property_scope",
    positionA: "unit_number",
    positionB: "building_or_combination",
    profileA: "unit_profile",
    profileB: "building_profile",
    resolution: "separate_assets",
  },
  {
    contradictionId: "CONTRA-SUFFIX-001",
    dimension: "business_suffix",
    positionA: "exclude_legal_suffix",
    positionB: "include_suffix",
    profileA: "brand_profile",
    profileB: "legal_entity_profile",
    resolution: "calculate_both",
  },
];

export const STARTER_DOCTRINE_AUTHORING: DoctrineAuthoringRelease = {
  actions: [
    ...ROOT_FIXTURES.map(action),
    {
      actionKey: "reflect.double-check-risk",
      instructions: { en: ["What preventable risk deserves a second check?"] },
      safetyTags: ["agency", "low_cost", "reflective", "reversible"],
      status: "active",
      version: "1.0.0",
    },
  ],
  contradictions: [...CONTRADICTIONS],
  locales: ["en"],
  promotions: [],
  releaseId: "starter-doctrine.2026-08-31.v1",
  rules: [
    ...ROOT_FIXTURES.map(rootRule),
    {
      actionKeys: ["reflect.double-check-risk"],
      claims: {
        en: [
          "Cheiro associates compound 16 with a caution to use foresight; this is an attributed symbolic prompt, not a predicted event.",
        ],
        hi: [],
        or: [],
      },
      conditions: [
        { op: "eq", path: "fact.compound", value: 16 },
        { op: "eq", path: "fact.root", value: 7 },
      ],
      confidence: "medium",
      exclusions: [],
      metricId: "name_number",
      profileId: "cheiro_1926_v1",
      ruleId: "cheiro.name.compound-16.v1",
      safetyTags: ["agency", "attributed", "reflective"],
      sourceRefs: [
        {
          evidenceClass: "authoritative_practitioner",
          locator: "Cheiro 1926, compound table pp. 69-75; editorial referral set",
          sourceId: "SRC-CHEIRO-1926",
        },
      ],
      status: "active",
      themes: ["foresight", "risk_review"],
      valence: "tension",
      version: "1.0.0",
    },
  ],
  schemaVersion: "1.0.0",
  sources: [
    {
      creator: "Cheiro",
      locale: "en",
      sourceId: "SRC-CHEIRO-1926",
      sourceType: "practitioner_primary",
      status: "active",
      title: "Cheiro's Book of Numbers",
    },
    {
      creator: "Numerology platform research synthesis",
      locale: "en",
      sourceId: "SRC-POLICY-ROOT-ONTOLOGY",
      sourceType: "product_policy",
      status: "active",
      title: "Interpretation Database root-number theme ontology",
    },
  ],
};
